project_id = "rbdzinajiyswzdeoenil"

[functions.pay-with-credits]
verify_jwt = false

[functions.station-control]
verify_jwt = false

[functions.check-expired-sessions]
verify_jwt = false

[functions.generate-receipt]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.get-receipt-pdf]
verify_jwt = false

[functions.emqx-webhook]
verify_jwt = false
